### ISSUE TITLE
学习率

### ISSUE THREAD

**Issue by Lefulann** [KevinJ-Huang/FECNet#10]
学习率我从1e-4调到1e-3的时候，很容易出现PSNR波动的情况，（波动很大）请问您之前训练的时候出现过这种情况么。

**Comment by KevinJ-Huang** [comment]
你好，傅里叶变换对于学习率不是很鲁棒，很重要的原因是频谱上一点小的变动会引起整张图像上巨大的变化。所以实际我在训练的时候，是先训练得到一个差不多的模型，然后基于这个模型调整学习率和学习率变化规律连续微调几次
