### ISSUE TITLE
FiveK数据集做test

### ISSUE THREAD

**Issue by zzzres** [KevinJ-Huang/FECNet#11]
请问作者的FiveK数据集长和宽是剪裁成固定偶数了吗？不是偶数的话好像不太行，比如shape是（1,3，512,341）的话送到模型里会出错
![image](https://github.com/KevinJ-Huang/FECNet/assets/130723056/c287fe2a-e8f7-4531-8db5-c4e893de8d7b)

**Comment by KevinJ-Huang** [comment]
非常抱歉没能及时回复，这里我做的操作很简单，将其resize成最近的偶数倍，当然测试PSNR的时候，GT也要Resize到对应的倍数
