### ISSUE TITLE
特征图的提取位置和方式

### ISSUE THREAD

**Issue by renjianyanhuo** [KevinJ-Huang/FECNet#13]
作者您好，被论文中图4和图6的精美的作图和展示手段所吸引，想请教一下，这种特征图是怎么提取出来的，为什么背景是蓝色的（比如是几十个通道中的某个通道），还有就是提取的位置。是否方便分享一下特征提取部分的代码，非常感谢！

**Comment by aaaasan111** [comment]
Please refer https://github.com/KevinJ-Huang/ECLNet/issues/1#issuecomment-1853983634

**Comment by KevinJ-Huang** [comment]
Please refer https://github.com/KevinJ-Huang/ECLNet/issues/1#issuecomment-1853983634
