### ISSUE TITLE
代码复现问题

### ISSUE THREAD

**Issue by xiangyj50** [KevinJ-Huang/FECNet#7]
当我运行train.py 时出现了下图的问题
请问 experiments_root 是要怎么设置的
非常感谢！

![issue](https://github.com/KevinJ-Huang/FECNet/assets/49711006/cc28362b-ad26-47d9-b63f-323b309d9045)

**Comment by sunqing-code** [comment]
请问您解决了吗？

**Comment by KevinJ-Huang** [comment]
这个是basic_sr框架的代码问题，可以在代码最前面加上本地路径试试？
