### ISSUE TITLE
代码复现问题

### ISSUE THREAD

**Issue by YongKangCao** [KevinJ-Huang/FECNet#9]
可以分享一下lol数据集训练的细节吗？根据代码只训出来21点多，达不到原文23。

**Comment by KevinJ-Huang** [comment]
我映像里实际训练要不断的训，就是先训到一个比较高的值，然后接着继续训练，需要多一点的训练迭代次数（反正需要一点调参）。预训练模型在这里[https://drive.google.com/file/d/1Ocun9bXSpypjWFZee8EMs0tGilJ8mYPc/view?usp=sharing](url)

**Comment by Distances-1** [comment]
> 可以分享一下lol数据集训练的细节吗？根据代码只训出来21点多，达不到原文23。

你好，你用的lol v1还是v2的数据集，为什么我训出来才有15点多

**Comment by KevinJ-Huang** [comment]
抱歉之前没看到这个问题，用的应该是v2，这个训练效果和傅里叶操作稳定性有关系，可能你的环境对这个算子支持不是很稳定，我之前训练也遇到过跑崩的情况，所以加了很多小数操作。另外patch size大一点，batch size学习率之类的也懂可以改改
